BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS cookbooks (
  id integer PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS dishes (
  id integer PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS recipes (
  id integer PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS ingredients (
  id integer PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id integer PRIMARY KEY AUTOINCREMENT
);

COMMIT TRANSACTION;
